-- ============================================================
-- Super Brain - Full Supabase Schema
-- Run this ONCE in Supabase SQL Editor to set up all tables
-- ============================================================

-- Step 1: Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Step 2: Users table
CREATE TABLE IF NOT EXISTS public.users (
  id text PRIMARY KEY,
  name text,
  preferences jsonb DEFAULT '{}'::jsonb,
  is_onboarded boolean DEFAULT false,
  onboarding_step text DEFAULT 'start',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Step 3: Conversations table
CREATE TABLE IF NOT EXISTS public.conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  message text NOT NULL,
  response text NOT NULL,
  model_used text NOT NULL,
  timestamp timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Step 4: Memories table with pgvector
CREATE TABLE IF NOT EXISTS public.memories (
  id text PRIMARY KEY,
  user_id text REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  document_text text NOT NULL,
  embedding vector(768) NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Step 5: Cosine similarity RPC function for RAG
CREATE OR REPLACE FUNCTION match_memories (
  query_embedding vector(768),
  match_threshold float,
  match_count int,
  p_user_id text
)
RETURNS TABLE (
  id text,
  document_text text,
  similarity float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    memories.id,
    memories.document_text,
    1 - (memories.embedding <=> query_embedding) AS similarity
  FROM memories
  WHERE memories.user_id = p_user_id
    AND 1 - (memories.embedding <=> query_embedding) > match_threshold
  ORDER BY memories.embedding <=> query_embedding
  LIMIT match_count;
$$;
